# for travis-ci
# see also. https://travis-ci.org
git:
  submodules: false

language: php
sudo: required
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7.0

matrix:
  fast_finish: true
  exclude:
    - php: hhvm
      env: DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres # driver currently unsupported by HHVM
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: 5.3.3

addons:
  code_climate:
    repo_token: 6d8ba8f8af566e3a38debd843bc7b4f24a93667df2c7eab6acfc12c4db0db9f2

env:
  - DB=mysql USER=root DBNAME=myapp_test DBPASS=' ' DBUSER=root
  - DB=pgsql USER=postgres DBNAME=myapp_test DBPASS=password DBUSER=postgres

before_script:
  - composer self-update || true
  - composer install --dev --no-interaction -o
  - sh -c "if [ '$DB' = 'mysql' ]; then sh ./eccube_install.sh mysql none; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sh ./eccube_install.sh pgsql none; fi"

script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then phpunit --coverage-clover build/logs/clover.xml ; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^[57] ]]; then phpunit ; fi

after_script:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then ./vendor/bin/test-reporter ; fi

after_failure: 
  - 'cat app/log/site_`date +"%Y-%m-%d"`.log'
